executors:
    node:
        docker:
        - image: circleci/node:16.13.2

aliases:
    restore_cache: &restore_cache
        restore_cache:
            name: Restore Package Cache
            keys:
            - yarn-cache-netlify-{{ checksum "yarn.lock" }}

    install_dependencies: &install_dependencies
        run:
            name: Install dependencies
            command: yarn install

    save_cache: &save_cache
        save_cache:
            name: Save Package Cache
            key: yarn-cache-netlify-{{ checksum "yarn.lock" }}
            paths:
            - ./node_modules

version: 2.1

jobs:
    test:
        executor: node
        steps:
            - checkout
            - <<: *restore_cache
            - <<: *install_dependencies
            - <<: *save_cache
            - run:
                name: Run Tests
                command: yarn test:badge

    build:
        executor: node
        steps:
        - checkout
        - <<: *restore_cache
        - <<: *install_dependencies
        - run:
            name: Run Build
            command: yarn build
        - persist_to_workspace:
            root: ./
            paths:
                - build

    deploy:
        executor: node
        steps:
        - checkout
        - attach_workspace:
            at: ./
        - <<: *restore_cache
        - <<: *install_dependencies
        - run:
            name: Install netlify-cli
            command: sudo npm install -g --silent netlify-cli
        - run:
            name: Deploy to Netlify
            command: netlify deploy --dir=./build --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --prod

workflows:
    version: 2
    test_and_build_and_deploy:
        jobs:
            - test:
                filters:
                    branches:
                        only: master
            - build:
                requires:
                    - test
                filters:
                    branches:
                        only: master
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
